services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db 
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  db_data: